package ADSML.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.descriptor.AbstractEditorBuilder;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import ADSML.behavior.ScenarioPreviewFactory;

/*package*/ class Scenario_ScenarioPreview_EditorBuilder_a extends AbstractEditorBuilder {
  @NotNull
  private SNode myNode;

  public Scenario_ScenarioPreview_EditorBuilder_a(@NotNull EditorContext context, @NotNull SNode node) {
    super(context);
    myNode = node;
  }

  @NotNull
  @Override
  public SNode getNode() {
    return myNode;
  }

  /*package*/ EditorCell createCell() {
    return createCollection_0();
  }

  private EditorCell createCollection_0() {
    EditorCell_Collection editorCell = new EditorCell_Collection(getEditorContext(), myNode, new CellLayout_Horizontal());
    editorCell.setCellId("Collection_1z79n5_a");
    editorCell.setBig(true);
    setCellContext(editorCell);
    editorCell.addEditorCell(createJComponent_0());
    return editorCell;
  }
  private EditorCell createJComponent_0() {
    EditorCell editorCell = EditorCell_Component.createComponentCell(getEditorContext(), myNode, _QueryFunction_JComponent_1z79n5_a0a(), "JComponent_1z79n5_a0");
    editorCell.setCellId("JComponent_1z79n5_a0_0");
    return editorCell;
  }
  private JComponent _QueryFunction_JComponent_1z79n5_a0a() {
    JPanel containerPanel = new JPanel();
    containerPanel.setLayout(null);
    containerPanel.setPreferredSize(new Dimension(1200, 630));

    JScrollPane sp = new JScrollPane(ScenarioPreviewFactory.createViewPanel(myNode), JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
    sp.setBounds(10, 10, 1180, 611);
    containerPanel.add(sp);
    return containerPanel;
  }
}
