package VSCE.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Location_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Map_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Pedestrian_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Vehicle_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Weather_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new World_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        if (true) {
          if ("VSCE.editor.ObjectLocation".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new ObjectLocation());
          }
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x31f1ee35b6e22565L), MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x1bbc25780c2d9d03L), MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x31f1ee35b6e22563L), MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x31f1ee35b6e22562L), MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x2766873431527132L), MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x276687343152713cL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x31f1ee35b6e22561L)).seal();
}
