package VSCE.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Weather_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("weather = carla.WeatherParameters(\n");
    tgs.append("\t cloudyness=");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x2766873431527132L, 0x1bbc25780c2cc05dL, "cloudiness")));
    tgs.append(",\n");
    tgs.append("\t precipitation=");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x2766873431527132L, 0x1bbc25780c2d5809L, "precipitation")));
    tgs.append(",\n");
    tgs.append("\t sun_altitude_angle=");
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), MetaAdapterFactory.getContainmentLink(0xdff00f176c3e4647L, 0xae8bee0827edcb59L, 0x2766873431527132L, 0x1bbc25780c2d5829L, "sun_altitude_angle")));
    tgs.append(",\n");
    tgs.append(")");
  }
}
