package VSCE.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Location;
  private ConceptPresentation props_Map;
  private ConceptPresentation props_Object;
  private ConceptPresentation props_Pedestrian;
  private ConceptPresentation props_Vehicle;
  private ConceptPresentation props_Weather;
  private ConceptPresentation props_World;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Location:
        if (props_Location == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Location");
          props_Location = cpb.create();
        }
        return props_Location;
      case LanguageConceptSwitch.Map:
        if (props_Map == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("map");
          props_Map = cpb.create();
        }
        return props_Map;
      case LanguageConceptSwitch.Object:
        if (props_Object == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Object = cpb.create();
        }
        return props_Object;
      case LanguageConceptSwitch.Pedestrian:
        if (props_Pedestrian == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Pedestrian = cpb.create();
        }
        return props_Pedestrian;
      case LanguageConceptSwitch.Vehicle:
        if (props_Vehicle == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Vehicle = cpb.create();
        }
        return props_Vehicle;
      case LanguageConceptSwitch.Weather:
        if (props_Weather == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("weather");
          props_Weather = cpb.create();
        }
        return props_Weather;
      case LanguageConceptSwitch.World:
        if (props_World == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_World = cpb.create();
        }
        return props_World;
    }
    return null;
  }
}
