package VSCE.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Element = 0;
  public static final int Map = 1;
  public static final int Weather = 2;
  public static final int World = 3;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xdff00f176c3e4647L, 0xae8bee0827edcb59L);
    builder.put(0x27668734315270cdL, Element);
    builder.put(0x1bbc25780c2d9d03L, Map);
    builder.put(0x2766873431527132L, Weather);
    builder.put(0x276687343152713cL, World);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
