package ADSML.behavior;

/*Generated by MPS */

import java.util.List;

public class Road {
  private List<Point> leftBoundary;
  private List<Point> rightBoundary;

  public Road() {
  }

  public Road(List<Point> leftBoundary, List<Point> rightBoundary) {
    this.leftBoundary = leftBoundary;
    this.rightBoundary = rightBoundary;
  }

  public List<Point> getLeftBoundary() {
    return this.leftBoundary;
  }
  public void setLeftBoundary(List<Point> leftBoundary) {
    this.leftBoundary = leftBoundary;
  }
  public List<Point> getRightBoundary() {
    return this.rightBoundary;
  }
  public void setRightBoundary(List<Point> rightBoundary) {
    this.rightBoundary = rightBoundary;
  }
}
