package ADSML.behavior;

/*Generated by MPS */

import javax.swing.JPanel;
import org.jetbrains.mps.openapi.model.SNode;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class ScenarioPreviewFactory {
  public static JPanel createViewPanel(final SNode scenario) {
    return new JPanel() {
      @Override
      protected void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        setBackground(Color.getHSBColor(100, 100, 100));
      }

      @Override
      public Dimension getPreferredSize() {
        return new Dimension(800, 600);
      }
    };
  }
}
