package ADSML.behavior;

/*Generated by MPS */

import javax.swing.JPanel;
import org.jetbrains.mps.openapi.model.SNode;
import java.awt.Graphics;
import java.awt.Color;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import java.awt.Graphics2D;
import java.awt.Dimension;

public class ScenarioPreviewFactory {
  public static JPanel createViewPanel(final SNode scenario) {
    return new JPanel() {
      @Override
      protected void paintComponent(final Graphics graphics) {
        super.paintComponent(graphics);
        setBackground(Color.getHSBColor(100, 100, 100));
        SNodeOperations.getModel(scenario).getRepository().getModelAccess().runReadAction(new Runnable() {
          public void run() {
            ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(scenario, MetaAdapterFactory.getContainmentLink(0x703f16c8997b4d66L, 0x9edc3367cac7e880L, 0x1d7a144c8e374fecL, 0x6de5a419aceeb958L, "roadNetwork")), MetaAdapterFactory.getContainmentLink(0x703f16c8997b4d66L, 0x9edc3367cac7e880L, 0x6de5a419acee7af6L, 0x6de5a419acee7afdL, "roads"))).visitAll(new IVisitor<SNode>() {
              public void visit(SNode it) {
                Road__BehaviorDescriptor.draw_id3WQzMjiHXxu.invoke(it, (Graphics2D) graphics);
              }
            });
          }
        });
      }

      @Override
      public Dimension getPreferredSize() {
        return new Dimension(800, 600);
      }
    };
  }
}
